### ISSUE TITLE
How to run learned rewrite with VSCode?

### ISSUE THREAD

**Issue by qidanrui** [zhouxh19/LearnedRewrite#1]
Hi Xuanhe @zhouxh19,
I'm trying to utilize the VSCode on my MacBook to run the LearnedRewrite code, i.e. test.py. However, I encountered the following errors and maybe it is because of the import of packages?

<img width="1001" alt="Screen Shot 2023-10-24 at 2 11 17 PM" src="https://github.com/zhouxh19/LearnedRewrite/assets/10005367/d322ed40-a7d7-4ed0-b987-45b1154563bd">

Do I need to build the whole project with Maven? 

Best,
Danrui

**Comment by qidanrui** [comment]
I imported all jars in `calcite_core_main_jar` and it works. Thanks!

**Comment by XuanheZhou** [comment]
great:)
