### ISSUE TITLE
请问calcite预估cost时会将数据库的索引考虑进去吗？

### ISSUE THREAD

**Issue by m729448362** [zhouxh19/LearnedRewrite#2]

**Comment by XuanheZhou** [comment]
对没有考虑，calcite这部分在getCostRecordFromRelNode函数。另外其实pg对索引的估计也不太好，我们在autoindex文章里讨论了如何近似走b树索引的计算开销 https://dbgroup.cs.tsinghua.edu.cn/ligl/papers/icde2022-autoindex.pdf

<img width="282" alt="image" src="https://github.com/zhouxh19/LearnedRewrite/assets/17394639/c29d499c-b74c-4179-a4ba-d293740bd2bc">
